MC's prompt improvements
quixio/template-llm-support pull request #18
Opened 2024-01-05 08:08 UTC by merlin-quix

* Overrode the system message in the Llama2Chat class, so that it matches our use case (was using a default system message previously)
* Improved the prompts in the prompt.yaml files.
* added a "clean_text" function to remove some minor issue that the LLM tends to add

2024-01-05 08:50 UTC, SteveRosam requested changes

2024-01-05 08:50 UTC, SteveRosam commented on AI Customer Support Agent/main.py
> +    system_message=SystemMessage(content="You are a customer of a large electronics retailer called 'ACME electronics' who is trying to resolve an issue with a defective product that you purchased.")
this is the support agent file

2024-01-05 08:50 UTC, SteveRosam commented on AI Customer/main.py
> +        system_message=SystemMessage(content="You are a customer support agent for a large electronics retailer called 'ACME electronics'."))
This is the customer file

2024-01-07 18:32 UTC, merlin-quix commented on AI Customer/main.py
> +        system_message=SystemMessage(content="You are a customer support agent for a large electronics retailer called 'ACME electronics'."))
Issues are fixed now,

2024-01-08 12:40 UTC, SteveRosam approved these changes

2024-01-08 12:40 UTC, merged